# -*- coding: utf-8 -*-
"""VisualVgg16testfinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16myLjbDxbmKbWh2vSWJQrpyJk44Zgvzq
"""

#lineone:Visualizing VGG16 model 
#http://image-net.org/about-stats
#https://arxiv.org/pdf/1409.1556.pdf
#below code has been tested and executed only in colab.research.google.com .For faster execution please make sure you have enabled GPU from notebook settings before execution

#for visualising resnet50 model
!pip install -q pydot-ng
!pip install graphviz
!apt-get install graphviz

#for visvualizing resnet50 model
#note:below two packages should be imported before importing keras.
#https://stackoverflow.com/questions/49853303/how-to-install-pydot-graphviz-on-google-colab
import pydot_ng 
import graphviz

#you are importing preprocess_input and decode_predictions from vgg16 model
#remember each model has its own preprocess_input and decoding functions when you are replication this for other 
#models make sure you importing from respective model
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np

model=VGG16(weights='imagenet',include_top=True)
#if you change include_top=False predict wont work

#This is the VGG model which we used - a text based description
model.summary()

#for visualizing resnet50 model
from keras.utils.vis_utils import model_to_dot
from IPython.display import SVG

#block representation of the model
SVG(model_to_dot(model).create(prog='dot',format='svg'))